export default {
  name: "about",
  title: "About Page",
  type: "document",
  fields: [
    {
      name: "section1Heading",
      title: "Section 1 Heading",
      type: "string",
    },
    {
      name: "section1Paragraph",
      title: "Section 1 Paragraph",
      type: "text",
    },
    {
      name: "section1Subheading",
      title: "Section 1 Subheading",
      type: "string",
    },
    {
      name: "section1Button",
      title: "Section 1 Button",
      type: "string",
    },
    {
      name: "section2Heading",
      title: "Section 2 Heading",
      type: "string",
    },
    {
      name: "section2Paragraph",
      title: "Section 2 Paragraph",
      type: "text",
    },
    {
      name: "section2Paragraph1",
      title: "Section 2 Paragraph 1",
      type: "text",
    },
    {
      name: "section2Paragraph2",
      title: "Section 2 Paragraph 2",
      type: "text",
    },
    {
      name: "section3Heading",
      title: "Section 3 Heading",
      type: "string",
    },
    {
      name: "section3Paragraph",
      title: "Section 3 Paragraph",
      type: "text",
    },
    {
      name: "section3Subheading",
      title: "Section 3 Subheading",
      type: "string",
    },
    {
      name: "section3Button",
      title: "Section 3 Button",
      type: "string",
    },
    {
      name: "section4Heading",
      title: "Section 4 Heading",
      type: "string",
    },
    {
      name: "section4Paragraph",
      title: "Section 4 Paragraph",
      type: "text",
    },
    {
      name: "listItems",
      title: "List Items",
      type: "array",
      of: [{ type: "string" }],
    },
    {
      name: "section4Paragraph1",
      title: "Section 4 Paragraph 1",
      type: "text",
    },
    {
      name: "heroImageAlt",
      title: "Hero Image Alt Text",
      type: "string",
      description: "Alt text for the hero image (/man(1).png). Describes the image for accessibility.",
    },
    {
      name: "profileImageAlt",
      title: "Profile Image Alt Text",
      type: "string",
      description: "Alt text for the profile image (/man-3.png). Describes the image for accessibility.",
    },
    {
      name: "therapistHeadshotAlt",
      title: "Therapist Headshot Alt Text", 
      type: "string",
      description: "Alt text for the therapist headshot (/Lindsiemeek-headshots-atp-92-2.JPEG).",
    },
    {
      name: "decorativeImageAlt",
      title: "Decorative Flower Alt Text",
      type: "string", 
      description: "Alt text for the decorative flower image (/flower-1.png).",
    },
    {
      name: "valuesAccordion",
      title: "Values Accordion Items",
      type: "array",
      of: [{ type: "accordionItem" }],
      description: "Items for the 'Our Values' accordion section",
    },
    {
      name: "faqAccordion",
      title: "FAQ Accordion Items",
      type: "array",
      of: [{ type: "accordionItem" }],
      description: "Items for the 'Frequently Asked Questions' accordion section",
    },
    {
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      description: "Custom page title for search engines. Leave empty to use default.",
    },
    {
      name: "seoDescription",
      title: "SEO Description",
      type: "text",
      rows: 3,
      description: "Custom meta description for search engines (150-160 characters recommended). Leave empty to use default.",
    },
    {
      name: "seoKeywords",
      title: "SEO Keywords",
      type: "string",
      description: "Custom keywords for this page, separated by commas. Leave empty to use default.",
    },
    {
      name: "seoImageAlt",
      title: "Social Media Image Alt Text",
      type: "string",
      description: "Alt text for the default social media image. Describes the image for accessibility and SEO.",
    },
  ],
};
